import 'package:flutter/material.dart';

class SyntaxHighlighting {
  static const List<String> operators = [
    "abstract",
    "else",
    "import",
    "super",
    "as",
    "enum",
    "in",
    "switch",
    "assert",
    "export",
    "interface",
    "sync",
    "async",
    "extends",
    "is",
    "this",
    "await",
    "extension",
    "library",
    "throw",
    "break",
    "external",
    "mixin",
    "true",
    "case",
    "factory",
    "new",
    "try",
    "catch",
    "false",
    "null",
    "typedef",
    "class",
    "final",
    "on1",
    "var",
    "const",
    "finally",
    "operator",
    "void",
    "continue",
    "for",
    "part",
    "while",
    "covarient",
    "Function",
    "rethrow",
    "with",
    "default",
    "get",
    "return",
    "yield",
    "deffered",
    "hide",
    "set",
    "do",
    "if",
    "show",
    "dynamic",
    "implements",
    "static",
  ];

  static get codePatterns => {
        RegExp(r"\bmain\b"): Colors.deepPurpleAccent,
        RegExp(r'\".*\"'): Colors.deepPurpleAccent,
        RegExp(r'>.*'): Colors.red,
        RegExp(r"\B#[a-zA-Z0-9]+\b"): Colors.red,
        RegExp(r";.*"): Colors.green,
        RegExp(r"\("): Colors.blue,
        RegExp(r"\)"): Colors.blue,
        RegExp(r"\b(" + operators.join("|") + r")\b"): Colors.deepOrange,
      };
}
